build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: plugins/drone-ecs
    when:
      branch: master

plugin:
  name: ECS
  desc: Deploys or updates a project on AWS ECS
  type: deploy
  image: plugins/drone-ecs
  labels:
    - aws
    - paas